use crate::span::Span;

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

#[derive(Clone, Debug, PartialEq)]
pub enum InterpSegment {
    Text(String),
    Expr { src: String, offset: usize },
}

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Indent,
    Dedent,
    Newline,
    Eof,
    Ident(String),
    Int(i64),
    Float(f64),
    String(String),
    InterpString(Vec<InterpSegment>),
    Bool(bool),
    Null,
    DocComment(String),
    Keyword(Keyword),
    Punct(Punct),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Keyword {
    App,
    Service,
    At,
    Get,
    Post,
    Put,
    Patch,
    Delete,
    Fn,
    Type,
    Enum,
    Let,
    Var,
    Return,
    If,
    Else,
    Match,
    Case,
    For,
    In,
    While,
    Break,
    Continue,
    Import,
    From,
    As,
    Config,
    Migration,
    Table,
    Test,
    Body,
    And,
    Or,
    Without,
    Spawn,
    Await,
    Box,
}

impl Keyword {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "app" => Some(Keyword::App),
            "service" => Some(Keyword::Service),
            "at" => Some(Keyword::At),
            "get" => Some(Keyword::Get),
            "post" => Some(Keyword::Post),
            "put" => Some(Keyword::Put),
            "patch" => Some(Keyword::Patch),
            "delete" => Some(Keyword::Delete),
            "fn" => Some(Keyword::Fn),
            "type" => Some(Keyword::Type),
            "enum" => Some(Keyword::Enum),
            "let" => Some(Keyword::Let),
            "var" => Some(Keyword::Var),
            "return" => Some(Keyword::Return),
            "if" => Some(Keyword::If),
            "else" => Some(Keyword::Else),
            "match" => Some(Keyword::Match),
            "case" => Some(Keyword::Case),
            "for" => Some(Keyword::For),
            "in" => Some(Keyword::In),
            "while" => Some(Keyword::While),
            "break" => Some(Keyword::Break),
            "continue" => Some(Keyword::Continue),
            "import" => Some(Keyword::Import),
            "from" => Some(Keyword::From),
            "as" => Some(Keyword::As),
            "config" => Some(Keyword::Config),
            "migration" => Some(Keyword::Migration),
            "table" => Some(Keyword::Table),
            "test" => Some(Keyword::Test),
            "body" => Some(Keyword::Body),
            "and" => Some(Keyword::And),
            "or" => Some(Keyword::Or),
            "without" => Some(Keyword::Without),
            "spawn" => Some(Keyword::Spawn),
            "await" => Some(Keyword::Await),
            "box" => Some(Keyword::Box),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Punct {
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Colon,
    Dot,
    DotDot,
    Arrow,
    FatArrow,
    Assign,
    EqEq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Question,
    Bang,
    QuestionQuestion,
    QuestionBang,
}
